In [71]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [45]:

cd /content/drive/MyDrive/0colab/deep-learning-from-scratch

/content/drive/MyDrive/0colab/deep-learning-from-scratch


In [46]:

!git config --global user.email 'hoon765@hanyang.ac.kr'
!git config --global user.name 'jonghoonparkk'
!git add --all
!git commit -m '0'
!git push

[master 8e28c19] 0
 5 files changed, 4 insertions(+), 5 deletions(-)
 rewrite "\341\204\200\341\205\252\341\204\214\341\205\2461.ipynb" (82%)
 delete mode 100644 "\341\204\200\341\205\252\341\204\214\341\205\2461.ipynb\341\204\213\341\205\264 \341\204\211\341\205\241\341\204\207\341\205\251\341\206\253\341\204\213\341\205\264 \341\204\211\341\205\241\341\204\207\341\205\251\341\206\253"
 rename "\341\204\200\341\205\252\341\204\214\341\205\2461.ipynb\341\204\213\341\205\264 \341\204\211\341\205\241\341\204\207\341\205\251\341\206\253" => "\341\204\200\341\205\252\341\204\214\341\205\2462" (55%)
 copy "\341\204\200\341\205\252\341\204\214\341\205\2461.ipynb" => "\341\204\200\341\205\252\341\204\214\341\205\2463" (66%)
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.17 KiB | 170.00 KiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolvi

Deep Learning Assignment #1

High Performance Integrated Circuit Design Lab.

실행해보는 문제는 직접 실행하고, 그 캡쳐본 또는 코드 및 결과를 답변으로 제출하시면 됩니다.

# 1. (Chapter 1)

## 1.1. (넘파이 배열)



1.1.2. 브로드캐스트 기능에 대해서 설명하시오.

1.1.2.1. 2 차원 배열 * 스칼라 연산을 직접 실행해보고, 그 결과에 대해서 고찰하시오.

1.1.2.2. 2 차원 배열 * 1차원 배열 연산을 직접 실행해보고, 그 결과에 대해서 고찰하시오.

1.1.3. flatten 기능을 이용하여 2차원 배열을 1차원 배열로 변환해보고, 1차원 배열로 바꾸는 이유에 대해서 설명하시오.

### 1.1.1. 1 차원, 2차원 배열의 산술연산에 대해서 설명하고, 그 예시를 실행해보시오. 또한, dimension, shape, dtype 에 대해서 설명하시오.

In [64]:
# 1.1. (넘파이 배열)
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
y = np.array([2.0, 4.0, 6.0])

[1. 2. 3.]


In [58]:
x + y

array([3., 6., 9.])

In [61]:
x-y

array([-1., -2., -3.])

In [62]:
x/y

array([0.5, 0.5, 0.5])

In [63]:
x*y

array([ 2.,  8., 18.])

넘파이의 N차원 배열


넘파이는 1차원 배열(1줄로 늘어선 배열)뿐 아니라 다차원 배열도 작성할 수 있습니다. 예를 들어
2차원 배열(행렬)은 다음처럼 작성합니다.

In [70]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape) # 형상 shape
print(A.dtype) # 자료형 dtype

[[1 2]
 [3 4]]
(2, 2)
int64


방금 2×2의 A라는 행렬을 작성했습니다. 행렬의 형상은 shape으로, 행렬에 담긴 원소의 자료형은 dtype으로 알 수 있습니다.

### 1.1.2. 브로드캐스트 기능에 대해서 설명하시오.

넘파이에서는 형상이 다른 배열끼리도 계산할 수 있습니다. 앞의 예에서는 2×2 행렬 A에 스칼라값 10을 곱했습니다. 이때 [그림 1-1]과 같이 10이라는 스칼라값이 2×2 행렬로 확대된 후 연산이 이뤄집니다. 이 똑똑한 기능을 브로드캐스트(broadcast)라고 합니다.